### ISSUE TITLE
error TS2415: Class 'ODataEntityService<S>' incorrectly extends base class 'NgEntityService<S>'

### ISSUE THREAD

**Issue by YuvL** [rosostolato/akita-ng-odata-service#1]
Hi,
the TS2415 error occurred because there is no @ts-ignore directive in odata-entity.service.d.ts. 
Full error text below:
error TS2415: Class 'ODataEntityService< S>' incorrectly extends base class 'NgEntityService< S>'.
  Property 'resolveUrl' is private in type 'NgEntityService< S>' but not in type 'ODataEntityService< S>'.

**Comment by rosostolato** [comment]
@YuvL  Hi! thanks for the report.

Wich version of angular are you using?

**Comment by YuvL** [comment]
@rosostolato Angular 9.1.6

**Comment by rosostolato** [comment]
@YuvL I pushed version 1.0.1 that will use new version of `akita-ng-entity-service` that changes privates to protected, also removed `@ts-ignore` to make sure ts linting is correct.

Please, have a try to see if it solves.
