### ISSUE TITLE
EnableProdMode Bug?: 

### ISSUE THREAD

**Issue by NelsonLamprecht** [rosostolato/akita-ng-odata-service#2]
I've setup akita and akita-ng-odata-service and it works fine running locally but after building in prod mode with aot and optomizations, I get an error message about no provider for NgEntityServiceLoader.
NullInjectorError: StaticInjectorError(AppModule)[NgEntityServiceLoader].

I'm not using the ngentityserviceloader (yet...)
Is this required? What does the wiring look like for it?

---
Actually does this work with Akita 5 and angular 8?

**Comment by rosostolato** [comment]
That's weird... I can't see any limitation in working with angular 8 and akita 5. I will try to reproduce, but please try to add the service manually to provider on `app.module.ts` (or in any other module that makes more sense):

```ts
import { NgEntityServiceLoader } from '@datorama/akita-ng-entity-service';

@NgModule({
  ...
  providers: [
    ...
    NgEntityServiceLoader 
  ],
  bootstrap: [AppComponent]
})
export class AppModule {}
```

**Comment by NelsonLamprecht** [comment]
> It's weird... I can't see any limitation to work with angular 8 and akita 5. I will try to reproduce, but please try to add the service manually to provider on `app.module.ts` (or in any other module that makes more sense):
> 
> ```ts
> import { NgEntityServiceLoader } from '@datorama/akita-ng-entity-service';
> 
> @NgModule({
>   ...
>   providers: [
>     ...
>     NgEntityServiceLoader 
>   ],
>   bootstrap: [AppComponent]
> })
> export class AppModule {}
> ```

Initially that seemed to work by adding to my app.module providers...:
...
{ provide: NG_ENTITY_SERVICE_CONFIG, useValue: { baseUrl: 'api' } },
        NgEntityServiceLoader,
        NgEntityServiceNotifier

**Comment by rosostolato** [comment]
Excellent... will leave it open in case of the issue returns
