### ISSUE TITLE
Adding Pagination Plugin

### ISSUE THREAD

**Issue by cjhaviland** [rosostolato/akita-ng-odata-service#3]
Just wondering if there are any plans to integrate [Akita's Pagination Plugin](https://github.com/datorama/akita/blob/master/libs/akita/src/lib/plugins/paginator/paginatorPlugin.ts) to work with this OData Service or if there is a better way to do it?

**Comment by rosostolato** [comment]
Well... I haven't planned anything since we have the `paginate` method on the `odata-fluent-query` library: https://github.com/rosostolato/odata-fluent-query/blob/e8582355cee75387bb730c5154d1c0ead06ec702/src/builders/create-query.ts#L40

But if you have anything in mind and want to contribute, please be free!

**Comment by cjhaviland** [comment]
Hmm I'll see what I can figure out. The only reason I was thinking about using that plug in is because it does a lot of the leg work for getting the amount of pages from the count and perPage. It also does some nice caching for the pages that have already been pulled.

The plugin handles updating the store, but it needs a VERY specific data response model which doesn't really work with the current OData get method.

**Comment by cjhaviland** [comment]
So, I was actually able to get this mostly working without really changing anything. The problem though is that you feed the OData service method into the Plugin which then subscribes. I had to write a separate method that takes the return data from the OData service and maps it into what the plugin wants. This is all working fine expect for the fact that I have OData Entity Service AND the plugin both trying to change my store.

So the order of operations here is; OData Service retrieves data and writes to store -> data is piped and mapped into plugin format -> plugin uses data and then writes to store again.

There's a whole caching aspect to this, so if we change the filters or how many we want in Top then it will wipe the store and start fresh. This is the part I am struggling with because I basically need to tell the service method to either set, or upsert dynamically. I think.

**Comment by rosostolato** [comment]
hey @cjhaviland, did you have any progress on that so far? What are your thoughts about it?

**Comment by cjhaviland** [comment]
@rosostolato I actually got it working for what I need with existing functionality. I think... It feels janky to me but it works. I can't right now, but I can post the code I used and get your opinions on if it could be added to the library.

**Comment by rosostolato** [comment]
@cjhaviland great! That's a good idea. Also, try to update to version 2.0.0 which uses new version of the OData quey library with great performance improvements.

**Comment by rosostolato** [comment]
I will close it for now.
