### ISSUE TITLE
The configuration object is being ignored by the Get method of the ODataEntityService

### ISSUE THREAD

**Issue by DanielTokyo** [rosostolato/akita-ng-odata-service#4]
Hi, after updating to the latest version of the library, I started receiving a `Cannot read property 'map' of undefined` while trying to fetch data from my service. After doing some research I noticed that although the error itself is not thrown by this library, the latest version of the `ODataEntityService` has introduced a bug that causes the configuration object to get lost before calling Akita's code:

When calling the `Get` method with a single config parameter (e.g. `this.get({ query, mapResponseFn, append: true })`), the new code creates a `conf` variable out of the `idOrConfig` parameter, but doesn't pass it to the Akita method. The line in question is number 71:
`return super.get((isSingle ? idOrConfig : config) as any, config);`

When `isSingle` is `false`, the undefined `config` parameter gets passed to Akita, making it ignore all config, including the mapping function.

I believe the line should probably be:
`return super.get((isSingle ? idOrConfig : conf) as any, config);`

Please let me know if you need more information.

Thank you for your attention and for this great library!

**Comment by rosostolato** [comment]
Thank you, @DanielTokyo 

That was a typo error. Right now I don't have a sample project on the repo to create unit tests, so that's why I didn't find that typo. I just need to get time to create that.

I pushed v2.0.1 with a hotfix and deprecated v2.0.0
