### ISSUE TITLE
Array Utils?

### ISSUE THREAD

**Issue by cjhaviland** [rosostolato/akita-ng-odata-service#5]
In reading through the best practices there is a lot of talk about not splitting up into separate stores if you don't have to.

I have an entity that I expand once, and then each of those expanded entities get expanded again. So something like;

Group
--> UserGroup
  --> User

I want to try and use a single store for Group and Array Util to add a new UserGroup and when I add a new UserGroup I want to send a query to expand the return to include the User model as well. Is this currently possible?

**Comment by rosostolato** [comment]
Probably I didn't follow what you really want, but think it's possible. What you could do is use the UI State feat to expand data and Akita effects to dispatch actions to react to UserGroup changes.

https://datorama.github.io/akita/docs/ui

https://datorama.github.io/akita/docs/angular/effects

**Comment by cjhaviland** [comment]
To better explain, I am just trying to figure out how to utilize OData and Akita the best way. (Also, this won't match what I previously said because I explained that wrong..."

So I have a User Group class which includes a GroupID and a UserID. Since the User and UserGroup tables are a one-to-one relationship, I'd rather do an OData expand on the User's UserGroup rather than store all the UserGroups in separate store, then have to link the UserID and GroupID altogether. 

I think you're right with using Effects when updating a UserGroup. I just think it's going to bother me if I have NgOdataService for Users and a regular service for UserGroups to do CRUD stuff.
